[general]
email = ""

[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "light"
primaryColor = "#10a37f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"